mineadmin/MineAdmin-Vue

src/components/ma-crud/index.vue
src/utils/tool.js

新增curd组件属性expandSearch是否默认打开搜索栏目

新增curd组件属性expandSearch是否默认打开搜索栏目

---

src/components/ma-crud/components/column.vue

```
edit: {
show: (item) => {
return item.status == 2
},
api: openWithdraw.update,
auth: ['open:withdraw:update'],
},
```

增加add,edit,delete按钮show属性支持函数回调控制

---

src/components/ma-crud/components/search.vue
src/components/ma-form/formGroup.vue

search组件日期组件默认range范围搜索，修复一处bug

search组件日期组件默认range范围搜索，修复一处bug

---

.gitlab-ci.yml
Dockerfile
package.json

增加.gitlab-ci.yml

---

src/components/ma-form/index.vue

```
<template>
<div class="ma-content-block p-5"><ma-form ref="formRef" v-model="form" :options="options" :columns="columns" /></div>
</template>
<script setup>
import { ref } from 'vue'
import {loadDict} from "@cps/ma-form/js/networkRequest";
const form = ref({})
const options = ref({
onInit(){
const dictService = formRef.value.getDictService()
dictService.get('mianmao').loadDict({
// 调用某字典数据
name: 'attachment_type',
props: { label: 'title', value: 'key'},
})
dictService.get('mianmao').getRawDictData()
}
})
const formRef = ref({})
const columns = ref([
{
formType: 'grid',
customClass: ['mb-2'],
cols: [
{
span: 24,
formList: [{ formType: 'divider', title: '基础信息'}]
},
{
span: 3,
formList: [{ formType: 'upload', dataIndex: 'avatar', title: '免冠照片', hideLabel: true,}]
},
{
span: 21,
formList: …
```

新增ma-form组件,getDictService方法，新增onInit初始化方法

---

src/components/ma-crud/index.vue

Dev  curd组件新增方法getColumnService类

Dev  curd组件新增方法getColumnService类

---

src/components/ma-upload/components/image-upload.vue

图片回显时为定义赋值会错误，只修复了image-upload.vue错误，另外文件上传和分片上传应该也是有问题的 未修复

fix:修复图片回显时错误

---

src/i18n/index.js

翻译文件在语言包下可设置多层级文件夹并获取到翻译文件里的内容

获取翻译文件方法替换&递归获取多层级翻译文件内容

---

src/views/system/role/components/dataPermission.vue

[增加，以表的dept_id作为数据范围, 没有字段 不限制](https://github.com/netyum/MineAdmin-Vue/commit/4202b71d7bc24269e398aba11586b342e223138d)

增加，以表的dept_id作为数据范围, 没有字段 不限制

---

src/components/ma-form/formItem/form-sku.vue

弹出层需要自己调节大小， 
数据提交到后端自行处理接收数据
```
{
title: "sku",
dataIndex: "sku",
formType: "sku",
hide: true,
}
```
```
/**
* 列表
* @return ResponseInterface
* @throws \Psr\Container\ContainerExceptionInterface
* @throws \Psr\Container\NotFoundExceptionInterface
*/
#[GetMapping("index"), Permission("setting:product, setting:product:index")]
public function index(): ResponseInterface
{
$data = $this->service->getPageList($this->request->all());
$items = $data['items'];
$skus = [
[
'childProductId' => 0,
'childProductSpec' => [
'颜色' => '红色',
],
'childProductNo' => 'P_0',
'childProductStock' => 100,
'childProductPrice' => 100,
'childProductCost' => 100,
'isUse' => true,
],
[
'childProductId' => 1,
'childProductSpec' => [
'颜色' => '白色',
],
'childProductNo' => 'P_11',
'childProductStock' => 100, …
```

add:新增sku组件

---

src/components/ma-upload/components/chunk-upload.vue
src/components/ma-upload/components/file-upload.vue
src/components/ma-upload/components/image-upload.vue

1.多附件上传，回显异常
2.文件上传结果展示优化
3.图片上传排版优化
4.分块上传，块数较大时，进度条加载异常

fix:文件上传组件异常

---

src/components/ma-editor/index.vue

fix: tinymce style fontfamily fontsize

fix: tinymce style fontfamily fontsize

---

src/components/ma-crud/components/search.vue

导出resetSearch方法,方便crud组件使用,用于重置搜索表单

导出resetSearch方法,方便crud组件使用,用于重置搜索表单

---

src/router/webRouter.js
src/views/setting/autoform/index.vue
src/views/setting/code/index.vue

实现，代码生成器， 测试自动表单
方便快速实现， 测试预览功能，不用频繁下载代码调试

featrue test autoform

---

src/components/ma-form/js/networkRequest.js

fix：联动 url 参数与 params 参数冲突

---

src/components/ma-codeEditor/index.vue

代码编辑器光标回到原点

---

src/directives/role/index.js

角色指令节点删除方式

---

src/components/ma-crud/types/columns.ts

```FormDateType``` 修改为 ```FormDataType```

fix: 修改ma-crud columns types的类型拼写错误

---

src/components/ma-editor/index.vue

Enhanced the ma-editor with integrated image uploading, using uploadRequest for file handling. Now, it intelligently processes image URLs from server responses, provides improved error handling, and supports various storage configurations.

feat(ma-editor): Added Image Upload

---

src/views/appStore/components/app.vue
src/views/appStore/components/appDetail.vue
src/views/appStore/components/appList.vue

fix(修复下载插件失败): 修复下载插件失败，去除space空间字段
